using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Savory.Rss
{
    public static class Language
    {
        public const string Afrikaans = "af";
        public const string Belarusian = "be";
        public const string Chinese_Simplified = "zh-cn";
        public const string Czech = "cs";
        public const string Dutch_Belgium = "nl-be";
        public const string English_Australia = "en-au";
        public const string English_Ireland = "en-ie";
        public const string English_Phillipines = "en-ph";
        public const string English_UnitedKingdom = "en-gb";
        public const string Estonian = "et";
        public const string French = "fr";
        public const string French_France = "fr-fr";
        public const string French_Switzerland = "fr-ch";
        public const string German = "de";
        public const string German_Liechtenstein = "de-li";
        public const string Greek = "el";
        public const string Icelandic = "is";
        public const string Italian = "it";
        public const string Japanese = "ja";
        public const string Norwegian = "no";
        public const string Portuguese_Brazil = "pt-br";
        public const string Romanian_Moldova = "ro-mo";
        public const string Russian_Moldova = "ru-mo";
        public const string Slovak = "sk";
        public const string Spanish_Argentina = "es-ar";
        public const string Spanish_Colombia = "es-co";
        public const string Spanish_Ecuador = "es-ec";
        public const string Spanish_Honduras = "es-hn";
        public const string Spanish_Panama = "es-pa";
        public const string Spanish_PuertoRico = "es-pr";
        public const string Spanish_Venezuela = "es-ve";
        public const string Swedish_Sweden = "sv-se";
        public const string Albanian = "sq";
        public const string Bulgarian = "bg";
        public const string Chinese_Traditional = "zh-tw";
        public const string Danish = "da";
        public const string Dutch_Netherlands = "nl-nl";
        public const string English_Belize = "en-bz";
        public const string English_Jamaica = "en-jm";
        public const string English_SouthAfrica = "en-za";
        public const string English_UnitedStates = "en-us";
        public const string Faeroese = "fo";
        public const string French_Belgium = "fr-be";
        public const string French_Luxembourg = "fr-lu";
        public const string Galician = "gl";
        public const string German_Austria = "de-at";
        public const string German_Luxembourg = "de-lu";
        public const string Hawaiian = "haw";
        public const string Indonesian = "in";
        public const string Italian_Italy = "it-it";
        public const string Korean = "ko";
        public const string Polish = "pl";
        public const string Portuguese_Portugal = "pt-pt";
        public const string Romanian_Romania = "ro-ro";
        public const string Russian_Russia = "ru-ru";
        public const string Slovenian = "sl";
        public const string Spanish_Bolivia = "es-bo";
        public const string Spanish_CostaRica = "es-cr";
        public const string Spanish_ElSalvador = "es-sv";
        public const string Spanish_Mexico = "es-mx";
        public const string Spanish_Paraguay = "es-py";
        public const string Spanish_Spain = "es-es";
        public const string Swedish = "sv";
        public const string Turkish = "tr";
        public const string Basque = "eu";
        public const string Catalan = "ca";
        public const string Croatian = "hr";
        public const string Dutch = "nl";
        public const string English = "en";
        public const string English_Canada = "en-ca";
        public const string English_NewZealand = "en-nz";
        public const string English_Trinidad = "en-tt";
        public const string English_Zimbabwe = "en-zw";
        public const string Finnish = "fi";
        public const string French_Canada = "fr-ca";
        public const string French_Monaco = "fr-mc";
        public const string Gaelic = "gd";
        public const string German_Germany = "de-de";
        public const string German_Switzerland = "de-ch";
        public const string Hungarian = "hu";
        public const string Irish = "ga";
        public const string Italian_Switzerland = "it-ch";
        public const string Macedonian = "mk";
        public const string Portuguese = "pt";
        public const string Romanian = "ro";
        public const string Russian = "ru";
        public const string Serbian = "sr";
        public const string Spanish = "es";
        public const string Spanish_Chile = "es-cl";
        public const string Spanish_DominicanRep="es-do";
        public const string Spanish_Guatemala = "es-gt";
        public const string Spanish_Nicaragua = "es-ni";
        public const string Spanish_Peru = "es-pe";
        public const string Spanish_Uruguay = "es-uy";
        public const string Swedish_Finland = "sv-fi";
        public const string Ukranian = "uk";

    }
}
