<?xml version="1.0" encoding="utf-8"?><Database Name="HarrisBlog" Class="HarrisBlogDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=BLUEWIND\BLUESERVER;Initial Catalog=HarrisBlog;Integrated Security=True" SettingsObjectName="HarrisBlog.Repository.Properties.Settings" SettingsPropertyName="HarrisBlogConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.talk_image" Member="talk_image">
    <Type Name="talk_image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TalkId" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImageId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.talk" Member="talk">
    <Type Name="talk">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TalkId" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MsgContent" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="PosName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PosX" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PosY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.original_image" Member="original_image">
    <Type Name="original_image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="LocalFilePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="RemoteFilePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="FakeFilePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.corp_image" Member="corp_image">
    <Type Name="corp_image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CorpImageId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OriginalImageId" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Width" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UseFor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FileExtension" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LocalFilePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="RemoteFilePath" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Post">
    <Type Name="Post">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ename" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PostType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MarkdownBody" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="HtmlBody" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CoverImgUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastUpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DataStatus" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>